# Generated by Django 3.1.7 on 2021-03-24 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'vc_comunas',
            },
        ),
        migrations.CreateModel(
            name='PollingPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Polling place')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polling_places', to='votes_counter.comuna')),
            ],
            options={
                'verbose_name': 'Polling place',
                'verbose_name_plural': 'Polling places',
                'db_table': 'vc_polling_places',
            },
        ),
        migrations.CreateModel(
            name='PollingPlaceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Polling place table')),
                ('polling_plpace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='votes_counter.pollingplace')),
            ],
            options={
                'verbose_name': 'Polling place table',
                'verbose_name_plural': 'Polling places tables',
                'db_table': 'vc_polling_placesgettextables',
            },
        ),
        migrations.CreateModel(
            name='UserCandidate',
            fields=[
                ('is_candidate', models.BooleanField(default=False, verbose_name='This user is candidate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='candidate', serialize=False, to='auth.user', verbose_name='user')),
            ],
            options={
                'verbose_name': 'Candidate user config',
                'verbose_name_plural': 'Candidate users config',
                'db_table': 'vc_user_candidates',
            },
        ),
        migrations.CreateModel(
            name='Votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Votes count')),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='votes', to=settings.AUTH_USER_MODEL)),
                ('polling_place_table', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='votes', to='votes_counter.pollingplacetable')),
            ],
            options={
                'verbose_name': 'Votes',
                'verbose_name_plural': 'Votes',
                'db_table': 'vc_polling_places_tables_votes',
            },
        ),
    ]
