# Generated by Django 3.1.7 on 2021-03-28 04:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes_counter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollingplacetable',
            old_name='polling_plpace',
            new_name='polling_place',
        ),
        migrations.AlterUniqueTogether(
            name='votes',
            unique_together={('polling_place_table', 'candidate')},
        ),
        migrations.AlterModelTable(
            name='pollingplacetable',
            table='vc_polling_places_tables',
        ),
    ]
