# Generated by Django 3.1.7 on 2021-03-28 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes_counter', '0002_typos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votes',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='votes', to='votes_counter.usercandidate'),
        ),
        migrations.AlterField(
            model_name='votes',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Votes count'),
        ),
    ]
