# Generated by Django 3.1.7 on 2021-04-12 03:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes_counter', '0003_vote__candidate__fk_fix'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'ordering': ('name',), 'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='pollingplace',
            options={'ordering': ('name',), 'verbose_name': 'Polling place', 'verbose_name_plural': 'Polling places'},
        ),
        migrations.AlterModelOptions(
            name='pollingplacetable',
            options={'ordering': ('name',), 'verbose_name': 'Polling place table', 'verbose_name_plural': 'Polling places tables'},
        ),
        migrations.AddField(
            model_name='usercandidate',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
