# Generated by Django 3.1.7 on 2021-05-15 23:27

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes_counter', '0004_user_candidate__color'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('color', colorfield.fields.ColorField(default='#444', max_length=18)),
            ],
            options={
                'verbose_name': 'List',
                'verbose_name_plural': 'Lists',
                'db_table': 'vc_lists',
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='usercandidate',
            name='color',
            field=colorfield.fields.ColorField(default='#444', max_length=18),
        ),
        migrations.AddField(
            model_name='usercandidate',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='votes_counter.list', verbose_name='List'),
        ),
    ]
